{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xinbida.wukongim",
    "module": "WKIMLib_local",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619513,
          "sha512": "1343a1dbdced7c2522276eb96f64154cf71a8ea0b6d2d3916c2086dc033e5fa58c3c20c3d2d46692d4bbefdd41633d5afe008b6f70324e0c9cec686a465623ff",
          "sha256": "73a9967a0646e688f68711d14a36540742de517dd2bb54cc93a0816ce449bd0c",
          "sha1": "0db92db1e267b589c7cdda81cf1f1e4c4e91e72a",
          "md5": "28971ab006836790ac22bd70bcbd64a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619513,
          "sha512": "1343a1dbdced7c2522276eb96f64154cf71a8ea0b6d2d3916c2086dc033e5fa58c3c20c3d2d46692d4bbefdd41633d5afe008b6f70324e0c9cec686a465623ff",
          "sha256": "73a9967a0646e688f68711d14a36540742de517dd2bb54cc93a0816ce449bd0c",
          "sha1": "0db92db1e267b589c7cdda81cf1f1e4c4e91e72a",
          "md5": "28971ab006836790ac22bd70bcbd64a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7-sources.jar",
          "url": "WKIMLib_local-1.0.7-sources.jar",
          "size": 329829,
          "sha512": "42b9e5c4f9b883895e1988da4f8a9a3bd50ba9444da657df09facafc21754595b3dddfdeba6933bcf05bc6dc4e095e0a92a284d55183e8d97b920f0054948460",
          "sha256": "e969812abf444c8e5c84e3bb01a2b24038a27ff5bb68d3069b3570a204b9a405",
          "sha1": "5213ab678cac393bf7d0da3d340ddc43a28294a1",
          "md5": "58de0c2f13f1422c82dfd191046563f0"
        }
      ]
    }
  ]
}
