{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xinbida.wukongim",
    "module": "WKIMLib_local",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619450,
          "sha512": "e3b3bdf7e99fcffca5ff40b7d2c515e43af1975ec277883d7c3b80388253e632cf644dad984debdc92d3760e0b7c04a5ecce16c62ff9d066ef9b5c7e1f4737c9",
          "sha256": "f1f8b7a5b49748f3f6b4765508bbae49351a04c756efb7cab1c36996fdc6fc32",
          "sha1": "dd1019d67fe7ab08a9533e3a2d4522c837e2ae60",
          "md5": "1ee8fd344f3bee13dedc2412ea85c8a1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.5.4"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619450,
          "sha512": "e3b3bdf7e99fcffca5ff40b7d2c515e43af1975ec277883d7c3b80388253e632cf644dad984debdc92d3760e0b7c04a5ecce16c62ff9d066ef9b5c7e1f4737c9",
          "sha256": "f1f8b7a5b49748f3f6b4765508bbae49351a04c756efb7cab1c36996fdc6fc32",
          "sha1": "dd1019d67fe7ab08a9533e3a2d4522c837e2ae60",
          "md5": "1ee8fd344f3bee13dedc2412ea85c8a1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7-sources.jar",
          "url": "WKIMLib_local-1.0.7-sources.jar",
          "size": 328923,
          "sha512": "c57204b220011558736e6372bb2542ab9582cd2c75da10df867746a475fd96b26198bb58b395a5d03d8d5f5174e43ab0b27536926279ea308aa2681ede1b2f7b",
          "sha256": "fc1443c43330c3e40a8a2b0a6041419b3c5361a88eb4592d90fec48e622c147c",
          "sha1": "9adffa480b12d4cf387d65ab45c57f280d4279bb",
          "md5": "5d168b3a13b32030e8635e7ebeeb842e"
        }
      ]
    }
  ]
}
