{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xinbida.wukongim",
    "module": "WKIMLib_local",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619745,
          "sha512": "235f469298429751b299f1b956f7c46dfd3bcea3fd2dd240859d7fbcbf5daa866d8ec5980c5bd4681dcd70e18a41434538aa7ab625694dc940309d0667d86b67",
          "sha256": "dff199d5a7e342255c74a0639eeeba2c98f5e0844968074d12c92b5adf6ea140",
          "sha1": "5d9af4f1269d318792cab589bb2fb80e6a5cc0ea",
          "md5": "c14ed31abb9a31739ed237fde77d3ca3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.5.4"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "WKIMLib_local-1.0.7.aar",
          "url": "WKIMLib_local-1.0.7.aar",
          "size": 619745,
          "sha512": "235f469298429751b299f1b956f7c46dfd3bcea3fd2dd240859d7fbcbf5daa866d8ec5980c5bd4681dcd70e18a41434538aa7ab625694dc940309d0667d86b67",
          "sha256": "dff199d5a7e342255c74a0639eeeba2c98f5e0844968074d12c92b5adf6ea140",
          "sha1": "5d9af4f1269d318792cab589bb2fb80e6a5cc0ea",
          "md5": "c14ed31abb9a31739ed237fde77d3ca3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "WKIMLib_local-1.0.7-sources.jar",
          "url": "WKIMLib_local-1.0.7-sources.jar",
          "size": 329297,
          "sha512": "3986f614c58519679f099e8f3fa51e97eb836d03d2c3ac16c9bc5a068ca8788aeef58013543d890c74c1e28fafbfbe92ac01f54de67b3d7ec64f960b25f88f76",
          "sha256": "16ff7a8390ab7dc4830fdae72c918efb0bc711af52bd2405947a68aac9ef8f8b",
          "sha1": "e60da7ae73465fa023111466d6be1831d9c5e05d",
          "md5": "5dbf087c85cf4772c3e3c25ad17e6788"
        }
      ]
    }
  ]
}
